"""
Central registry of endpoints monitored by the daily API Health Suite.

v7: expanded from the INJIN HRMS Postman collection (421 total requests
reviewed). Three groups below:
  1. ORIGINAL 10 — the hand-built starting set (unchanged)
  2. CLEAN ADDITIONS — safe GET reads, no dynamic ID needed
  3. RESOLVABLE ADDITIONS — need a real record ID first; resolved at
     runtime by calling a 'source' list endpoint and extracting an ID
     (see RESOLVER_CONFIG and utils/health_id_resolver.py)

38 endpoints from the Postman collection are DELIBERATELY EXCLUDED —
see postman_excluded_needs_review.xlsx for the list and why each needs
your input before it can be added safely.
"""

from datetime import date


def current_month_param():
    return {"month": date.today().strftime("%Y-%m")}


def leave_requests_params():
    return {"page": 1, "per_page": 10, "order": "desc"}


def tickets_params():
    return {"page": 1, "per_page": 10}


def notifications_params():
    return {"page": 1, "per_page": 10, "unread_only": "false"}


AUTH_PROFILES = {
    "employee": {
        "username_env": "HEALTH_USER_USERNAME",
        "password_env": "HEALTH_USER_PASSWORD",
    },
}

DEFAULT_SLA_MS = 2000

# ---------------------------------------------------------------------------
# RESOLVER_CONFIG: for RESOLVABLE ADDITIONS below. Each key is a path
# variable name; 'source_path' is a GET endpoint (already in this registry)
# that returns a list — we take the FIRST item and try each field name in
# 'fields' (in order) until one exists in that item, and use its value.
#
# IMPORTANT: 'fields' are best-guess field names. After your first real run,
# check the health report / logs for any 'ID resolution failed' errors and
# adjust the field name list to match your API's actual response shape.
# ---------------------------------------------------------------------------
RESOLVER_CONFIG = {
    "announcement_uuid": {
        "source_path": "/api/hr/announcements",
        "fields": [
            "announcement_uuid",
            "uuid",
            "id"
        ]
    },
    "employee_uuid": {
        "source_path": "/api/hr/users",
        "fields": [
            "employee_uuid",
            "uuid",
            "id"
        ]
    },
    "event_uuid": {
        "source_path": "/api/admin/notifications/events",
        "fields": [
            "event_uuid",
            "uuid",
            "id"
        ]
    },
    "financial_year": {
        "source_path": "/api/admin/financial-years",
        "fields": [
            "financial_year",
            "year",
            "label"
        ]
    },
    "legal_entity_uuid": {
        "source_path": "/api/admin/legal-entities",
        "fields": [
            "legal_entity_uuid",
            "uuid",
            "id"
        ]
    },
    "payslip_uuid": {
        "source_path": "/api/hr/payslips",
        "fields": [
            "payslip_uuid",
            "uuid",
            "id"
        ]
    },
    "run_uuid": {
        "source_path": "/api/admin/payroll/runs",
        "fields": [
            "run_uuid",
            "uuid",
            "id"
        ]
    },
    "member_uuid": {
        "source_path": "/api/me/team/roster",
        "fields": [
            "member_uuid",
            "employee_uuid",
            "uuid",
            "id"
        ]
    }
}


ENDPOINTS = [
    # =========================================================================
    # ORIGINAL 10 — hand-built starting set
    # =========================================================================
    {
        "name": "login",
        "action": "User Login / Authentication",
        "method": "POST",
        "path": "/api/auth/login",
        "auth_profile": "None",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1500,
    },
    {
        "name": "me",
        "action": "Fetch Logged-in User Profile",
        "method": "GET",
        "path": "/api/me",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1000,
    },
    {
        "name": "get_user_details",
        "action": "Fetch Extended User Details",
        "method": "GET",
        "path": "/api/me/getUserDetails",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1000,
    },
    {
        "name": "employee_leave_policy",
        "action": "Fetch Leave Policy",
        "method": "GET",
        "path": "/api/me/employee-leave-policy",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "employee_holiday_policy",
        "action": "Fetch Holiday Policy",
        "method": "GET",
        "path": "/api/me/employee-holiday-policy",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "attendance_monthly",
        "action": "Fetch Monthly Attendance",
        "method": "GET",
        "path": "/api/me/attendance",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        "params": current_month_param,
    },
    {
        "name": "leave_requests",
        "action": "Fetch Leave Requests",
        "method": "GET",
        "path": "/api/me/leave-requests",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        "params": leave_requests_params,
    },
    {
        "name": "ticketing_tickets",
        "action": "Fetch Support Tickets",
        "method": "GET",
        "path": "/api/me/ticketing/tickets",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        "params": tickets_params,
    },
    {
        "name": "notifications",
        "action": "Fetch Notifications",
        "method": "GET",
        "path": "/api/me/notifications",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        "params": notifications_params,
    },
    {
        "name": "hr_payslips",
        "action": "Fetch Payslips",
        "method": "GET",
        "path": "/api/hr/payslips",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
    },
    # =========================================================================
    # CLEAN ADDITIONS from Postman collection (108 endpoints)
    # Safe GET reads, no dynamic ID needed, auth normalized to 'employee'
    # since your account has access across employee/hr/admin scopes.
    # =========================================================================
    {
        "name": "login_pm",
        "action": 'User Login / Authentication',
        "method": "POST",
        "path": '/api/auth/login',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1500,
    },
    {
        "name": "me_pm",
        "action": 'Fetch Logged-in User Profile',
        "method": "GET",
        "path": '/api/me',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1000,
    },
    {
        "name": "get_user_details_pm",
        "action": 'Fetch Extended User Details',
        "method": "GET",
        "path": '/api/me/getUserDetails',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1000,
    },
    {
        "name": "employee_leave_policy_pm",
        "action": 'Fetch Leave Policy',
        "method": "GET",
        "path": '/api/me/employee-leave-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "employee_holiday_policy_pm",
        "action": 'Fetch Holiday Policy',
        "method": "GET",
        "path": '/api/me/employee-holiday-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "attendance_monthly_pm",
        "action": 'Fetch Monthly Attendance',
        "method": "GET",
        "path": '/api/me/attendance',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "leave_requests_pm",
        "action": 'Fetch Leave Requests',
        "method": "GET",
        "path": '/api/me/leave-requests',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "ticketing_tickets_pm",
        "action": 'Fetch Support Tickets',
        "method": "GET",
        "path": '/api/me/ticketing/tickets',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "notifications_pm",
        "action": 'Fetch Notifications',
        "method": "GET",
        "path": '/api/me/notifications',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "hr_payslips_pm",
        "action": 'Fetch Payslips',
        "method": "GET",
        "path": '/api/hr/payslips',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
    },
    {
        "name": "fetch_ticket_types",
        "action": 'Fetch Ticket Types',
        "method": "GET",
        "path": '/admin/ticketing/ticket-types',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_invite_list",
        "action": 'Fetch Invite List',
        "method": "GET",
        "path": '/api/hr/offers',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "onboarding_approved",
        "action": 'Onboarding Approved',
        "method": "GET",
        "path": '/api/hr/onboarding-approved',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_users_list",
        "action": 'Fetch Users List',
        "method": "GET",
        "path": '/api/hr/users',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_user_detail_by_user",
        "action": 'Fetch User Detail By User',
        "method": "GET",
        "path": '/api/me/users',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_attendance_summary",
        "action": 'Fetch Attendance Summary',
        "method": "GET",
        "path": '/api/hr/attendance/',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_full_manager_list",
        "action": 'Fetch Full Manager List',
        "method": "GET",
        "path": '/api/hr/users/managers-list',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "metrics",
        "action": 'Metrics',
        "method": "GET",
        "path": '/api/hr/dashboard/metrics',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "workforce_snapshot",
        "action": 'Workforce Snapshot',
        "method": "GET",
        "path": '/api/hr/dashboard/workforce-snapshot',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "attendance_overview",
        "action": 'Attendance Overview',
        "method": "GET",
        "path": '/api/hr/dashboard/attendance-overview',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "pending_approvals",
        "action": 'Pending Approvals',
        "method": "GET",
        "path": '/api/hr/dashboard/pending-approvals',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "recent_joiners",
        "action": 'Recent Joiners',
        "method": "GET",
        "path": '/api/hr/dashboard/recent-joiners',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "today_onboarding",
        "action": 'Today Onboarding',
        "method": "GET",
        "path": '/api/hr/dashboard/today-onboarding',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "celebrations",
        "action": 'Celebrations',
        "method": "GET",
        "path": '/api/hr/dashboard/celebrations',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "list_announcements_hr_admin",
        "action": 'List Announcements (HR admin)',
        "method": "GET",
        "path": '/api/hr/announcements',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "my_announcements_feed_employee",
        "action": 'My Announcements Feed (Employee)',
        "method": "GET",
        "path": '/api/me/announcements',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "list_templates",
        "action": 'List Templates',
        "method": "GET",
        "path": '/api/hr/announcement-templates',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "self_permissions",
        "action": 'Self Permissions',
        "method": "GET",
        "path": '/api/me/permissions',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_user_attendance_config",
        "action": 'Fetch User Attendance Config',
        "method": "GET",
        "path": '/api/me/attendance-config',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_hr_level_employee_leave_policy",
        "action": 'Fetch Hr Level Employee Leave Policy',
        "method": "GET",
        "path": '/api/hr/hr-employee-leave-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_all_employee_applied_leave",
        "action": 'Fetch All Employee Applied Leave',
        "method": "GET",
        "path": '/api/me/fetch-all-applied-leave',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_hr_level_applied_leave",
        "action": 'Fetch Hr Level Applied Leave',
        "method": "GET",
        "path": '/api/hr/fetch-all-applied-leave',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_tickets",
        "action": 'Fetch Tickets',
        "method": "GET",
        "path": '/api/ticketing/tickets',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "upcoming_events",
        "action": 'Upcoming Events',
        "method": "GET",
        "path": '/api/me/dashboard/upcoming-events',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_pending_tickets",
        "action": 'Fetch Pending Tickets',
        "method": "GET",
        "path": '/api/ticketing/pending-approvals',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "my_team_manager_direct_reports",
        "action": 'My Team (Manager + Direct Reports)',
        "method": "GET",
        "path": '/api/me/team',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "organisation_chart_flat_list",
        "action": 'Organisation Chart (Flat List)',
        "method": "GET",
        "path": '/api/me/organisation',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "organisation_chart_nested_tree",
        "action": 'Organisation Chart (Nested Tree)',
        "method": "GET",
        "path": '/api/me/organisation/tree',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "team_dashboard",
        "action": 'Team Dashboard',
        "method": "GET",
        "path": '/api/me/team/dashboard',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "team_roster_full_subtree",
        "action": 'Team Roster (Full Subtree)',
        "method": "GET",
        "path": '/api/me/team/roster',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "pending_leave_requests_mine_to_approve",
        "action": 'Pending Leave Requests (Mine to Approve)',
        "method": "GET",
        "path": '/api/me/team/leave-requests',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "team_leave_calendar_month_subtree",
        "action": 'Team Leave Calendar (Month, Subtree)',
        "method": "GET",
        "path": '/api/me/team/leave-calendar',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "team_leave_balance",
        "action": 'Team Leave Balance',
        "method": "GET",
        "path": '/api/me/team/leave-balance',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "team_attendance_calendar_month_subtree",
        "action": 'Team Attendance Calendar (Month, Subtree)',
        "method": "GET",
        "path": '/api/me/team/attendance',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "team_attendance_today",
        "action": 'Team Attendance — Today',
        "method": "GET",
        "path": '/api/me/team/attendance/today',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "unified_pending_approvals",
        "action": 'Unified Pending Approvals',
        "method": "GET",
        "path": '/api/me/team/approvals',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "get_unread_count",
        "action": 'Get Unread Count',
        "method": "GET",
        "path": '/api/me/notifications/unread-count',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "get_my_mute_preferences",
        "action": 'Get My Mute Preferences',
        "method": "GET",
        "path": '/api/me/notification-preferences',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_permissions",
        "action": 'Fetch Permissions',
        "method": "GET",
        "path": '/api/admin/permissions/matrix',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: RBAC
    },
    {
        "name": "fetch_roles",
        "action": 'Fetch Roles',
        "method": "GET",
        "path": '/api/admin/roles',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: RBAC
    },
    {
        "name": "fetch_attendance_default_list",
        "action": 'Fetch Attendance Default List',
        "method": "GET",
        "path": '/api/admin/attendance-defaults',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Master Data / Attendance Default
    },
    {
        "name": "fetch_attendance_default",
        "action": 'Fetch Attendance Default',
        "method": "GET",
        "path": '/api/admin/attendance-defaults/current',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Master Data / Attendance Default
    },
    {
        "name": "fetch_master_option_list",
        "action": 'Fetch Master Option List',
        "method": "GET",
        "path": '/api/admin/master-options/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Master Options
    },
    {
        "name": "fetch_master_option_dependent_list",
        "action": 'Fetch Master Option Dependent List',
        "method": "GET",
        "path": '/api/admin/master-options/mode_type',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Master Options
    },
    {
        "name": "fetch_ip_address_list",
        "action": 'Fetch IP Address List',
        "method": "GET",
        "path": '/api/admin/ip-addresses',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / IP Address
    },
    {
        "name": "fetch_attendance_source_list",
        "action": 'Fetch  Attendance Source List',
        "method": "GET",
        "path": '/api/admin/attendance-source',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Master Data / Attendance Source
    },
    {
        "name": "fetch_work_mode_list",
        "action": 'Fetch  Work Mode List',
        "method": "GET",
        "path": '/api/admin/work-mode',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Work Mode
    },
    {
        "name": "fetch_attendance_policy_list",
        "action": 'Fetch  Attendance Policy List',
        "method": "GET",
        "path": '/api/admin/attendance-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Master Data / Attendance Policy
    },
    {
        "name": "fetch_break_policy_list",
        "action": 'Fetch  Break Policy List',
        "method": "GET",
        "path": '/api/admin/break-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Break Policy
    },
    {
        "name": "fetch_shift_list",
        "action": 'Fetch Shift List',
        "method": "GET",
        "path": '/api/admin/shifts',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Shift
    },
    {
        "name": "fetch_salary_structure_list",
        "action": 'Fetch Salary Structure List',
        "method": "GET",
        "path": '/api/admin/salary-structures',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Master Data / Salary Structure
    },
    {
        "name": "salary_structure_meta",
        "action": 'Salary Structure Meta',
        "method": "GET",
        "path": '/api/admin/salary-structures/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Master Data / Salary Structure
    },
    {
        "name": "fetch_pay_component_group_list",
        "action": 'Fetch Pay Component Group List',
        "method": "GET",
        "path": '/api/admin/pay-component-groups',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Component Group
    },
    {
        "name": "pay_component_group_meta",
        "action": 'Pay Component Group Meta',
        "method": "GET",
        "path": '/api/admin/pay-component-groups/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Component Group
    },
    {
        "name": "fetch_pay_component_rule_list",
        "action": 'Fetch Pay Component Rule List',
        "method": "GET",
        "path": '/api/admin/pay-component-rules',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Components Rule
    },
    {
        "name": "pay_component_rule_meta",
        "action": 'Pay Component Rule Meta',
        "method": "GET",
        "path": '/api/admin/pay-component-rules/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Components Rule
    },
    {
        "name": "fetch_pay_component_list",
        "action": 'Fetch Pay Component List',
        "method": "GET",
        "path": '/api/admin/pay-components',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Component
    },
    {
        "name": "pay_component_meta",
        "action": 'Pay Component Meta',
        "method": "GET",
        "path": '/api/admin/pay-components/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Component
    },
    {
        "name": "fetch_pay_range_list",
        "action": 'Fetch Pay Range List',
        "method": "GET",
        "path": '/api/admin/pay-ranges',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Range
    },
    {
        "name": "fetch_cost_center_list",
        "action": 'Fetch Cost Center List',
        "method": "GET",
        "path": '/api/admin/cost-centers',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Cost Center
    },
    {
        "name": "fetch_job_title_list",
        "action": 'Fetch Job Title List',
        "method": "GET",
        "path": '/api/admin/job-titles',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Job Title
    },
    {
        "name": "fetch_sub_function_list",
        "action": 'Fetch Sub Function List',
        "method": "GET",
        "path": '/api/admin/sub-functions',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Sub Function
    },
    {
        "name": "fetch_function_list",
        "action": 'Fetch Function List',
        "method": "GET",
        "path": '/api/admin/functions',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Function
    },
    {
        "name": "fetch_pay_grade_list",
        "action": 'Fetch Pay Grade List',
        "method": "GET",
        "path": '/api/admin/pay-grades',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Grade
    },
    {
        "name": "fetch_work_location_list",
        "action": 'Fetch Work Location List',
        "method": "GET",
        "path": '/api/admin/work-locations',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Work Location
    },
    {
        "name": "fetch_geo_zone_list",
        "action": 'Fetch Geo Zone List',
        "method": "GET",
        "path": '/api/admin/geozones',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Geo Zones
    },
    {
        "name": "fetch_employee_leave_approval",
        "action": 'Fetch Employee Leave Approval',
        "method": "GET",
        "path": '/api/admin/comp-off-requests',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Comp Off Request
    },
    {
        "name": "fetch_optional_holiday",
        "action": 'Fetch Optional Holiday',
        "method": "GET",
        "path": '/api/admin/optional-holiday-selections',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Optional Holiday Selection
    },
    {
        "name": "fetch_employee_leave_approval_2",
        "action": 'Fetch Employee Leave Approval',
        "method": "GET",
        "path": '/api/admin/leave-approval-workflows',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Leave Approval WorkFlow
    },
    {
        "name": "fetch_holiday_group",
        "action": 'Fetch Holiday Group',
        "method": "GET",
        "path": '/api/admin/holiday-groups/{uuid}',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Holiday Group
    },
    {
        "name": "fetch_financial_year",
        "action": 'Fetch Financial Year',
        "method": "GET",
        "path": '/api/admin/financial-years',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Financial Year Master
    },
    {
        "name": "get_active_year",
        "action": 'Get Active Year',
        "method": "GET",
        "path": '/api/admin/financial-years/active',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Financial Year Master
    },
    {
        "name": "fetch_leave_policy_assignemnt_list",
        "action": 'Fetch Leave Policy Assignemnt List',
        "method": "GET",
        "path": '/api/admin/leave-balance-ledger',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Leave Balance Ledger
    },
    {
        "name": "fetch_leave_group",
        "action": 'Fetch Leave Group',
        "method": "GET",
        "path": '/api/admin/policy-groups',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Leave Policy Group
    },
    {
        "name": "show_by_code",
        "action": 'Show By Code',
        "method": "GET",
        "path": '/api/admin/leave-types/code/CL',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Leave Type
    },
    {
        "name": "fetch_legal_entity_list",
        "action": 'Fetch Legal Entity List',
        "method": "GET",
        "path": '/api/admin/legal-entities',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Legal Entity
    },
    {
        "name": "fetch_hierarchy_level",
        "action": 'Fetch Hierarchy Level',
        "method": "GET",
        "path": '/api/admin/hierarchy-levels/{uuid}',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Hierarchy Levels
    },
    {
        "name": "fetch_workflows",
        "action": 'Fetch Workflows',
        "method": "GET",
        "path": '/api/admin/ticketing/workflows',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Ticketing / Workflows
    },
    {
        "name": "admin_show_tickets",
        "action": 'Admin Show Tickets',
        "method": "GET",
        "path": '/api/admin/ticketing/tickets',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Ticketing / Admin Tickets
    },
    {
        "name": "admin_show_tickets_comments",
        "action": 'Admin Show Tickets Comments',
        "method": "GET",
        "path": '/api/admin/ticketing/tickets/{uuid}/comments',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Ticketing / Admin Tickets
    },
    {
        "name": "cancel_tickets",
        "action": 'Cancel Tickets',
        "method": "GET",
        "path": '/api/admin/ticketing/tickets/{uuid}/cancel',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Ticketing / Admin Tickets
    },
    {
        "name": "fetch_document_list_copy",
        "action": 'Fetch Document List Copy',
        "method": "GET",
        "path": '/api/onboarding/meta/document-types',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Onboarding
    },
    {
        "name": "fetch_form_schema",
        "action": 'Fetch Form Schema',
        "method": "GET",
        "path": '/api/onboarding/meta/form-schema',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Onboarding
    },
    {
        "name": "fetch_meta_data",
        "action": 'Fetch Meta Data',
        "method": "GET",
        "path": '/api/onboarding/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Onboarding
    },
    {
        "name": "fetch_employee_attendance_policy_history",
        "action": 'Fetch Employee Attendance Policy History',
        "method": "GET",
        "path": '/api/hr/employees/{uuid}/attendance-config/history',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Human Resources / Attendance
    },
    {
        "name": "fetch_employee_attendance_day_override",
        "action": 'Fetch Employee Attendance Day Override',
        "method": "GET",
        "path": '/api/hr/employees/{employeeUuid}/attendance-override/2026-05-12',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Human Resources / Attendance
    },
    {
        "name": "fetch_direct_reportees",
        "action": 'Fetch Direct Reportees',
        "method": "GET",
        "path": '/api/hr/users/{uuid}/direct-reports',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Reporting Manager
    },
    {
        "name": "fetch_reporting_team",
        "action": 'Fetch Reporting Team',
        "method": "GET",
        "path": '/api/hr/users/{uuid}/team',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Reporting Manager
    },
    {
        "name": "fetch_reporting_chain",
        "action": 'Fetch Reporting Chain',
        "method": "GET",
        "path": '/api/hr/users/{uuid}/reporting-chain',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Reporting Manager
    },
    {
        "name": "fetch_employee_group",
        "action": 'Fetch Employee Group',
        "method": "GET",
        "path": '/api/hr/employee-holiday-group-assignments/{uuid}',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Human Resources / Holiday
    },
    {
        "name": "fetch_employee_week_off",
        "action": 'Fetch Employee Week Off',
        "method": "GET",
        "path": '/api/hr/employee-weekly-off-assignment/{uuid}',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Weekly Off
    },
    {
        "name": "fetch_employee_code_setting",
        "action": 'Fetch Employee Code Setting',
        "method": "GET",
        "path": '/api/admin/settings/employee-code',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: HRMS Settings / Employee Code
    },
    {
        "name": "fetch_app_timezone",
        "action": 'Fetch App Timezone',
        "method": "GET",
        "path": '/api/admin/settings/timezone',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: HRMS Settings / Timezone
    },
    {
        "name": "fetch_ui_color",
        "action": 'Fetch UI Color',
        "method": "GET",
        "path": '/api/admin/settings/ui-color',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: HRMS Settings / UI Color
    },
    {
        "name": "fetch_probation_notice",
        "action": 'Fetch Probation & Notice',
        "method": "GET",
        "path": '/api/admin/settings/hr-defaults',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: HRMS Settings / Probation & Notice
    },
    {
        "name": "list_runs",
        "action": 'List Runs',
        "method": "GET",
        "path": '/api/admin/payroll/runs',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 11. Payroll Runs
    },
    {
        "name": "list_all_events",
        "action": 'List All Events',
        "method": "GET",
        "path": '/api/admin/notifications/events',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Notifications / 1. Admin — Events
    },
    {
        "name": "list_delivery_logs_no_filters",
        "action": 'List Delivery Logs (no filters)',
        "method": "GET",
        "path": '/api/admin/notifications/logs',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Notifications / 4. Admin — Delivery Logs
    },
    # =========================================================================
    # RESOLVABLE ADDITIONS (34 endpoints)
    # path_template uses {var} placeholders, filled in at runtime by
    # utils/health_id_resolver.py using RESOLVER_CONFIG above.
    # =========================================================================
    {
        "name": "get_announcement_by_uuid",
        "action": 'Get Announcement by UUID',
        "method": "GET",
        "path_template": '/api/hr/announcements/{announcement_uuid}',
        "resolve_vars": ['announcement_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Announcements & Events
    },
    {
        "name": "get_config_history",
        "action": 'Get Config History',
        "method": "GET",
        "path_template": '/api/admin/payroll/config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 1. Payroll Config
    },
    {
        "name": "get_current_config",
        "action": 'Get Current Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/config/{legal_entity_uuid}/current',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 1. Payroll Config
    },
    {
        "name": "get_pf_config",
        "action": 'Get PF Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/pf-config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 2. PF Config
    },
    {
        "name": "get_gratuity_config",
        "action": 'Get Gratuity Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/gratuity-config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 3. Gratuity Config (NEW)
    },
    {
        "name": "get_esi_config",
        "action": 'Get ESI Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/esi-config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 4. ESI Config
    },
    {
        "name": "get_pt_slabs",
        "action": 'Get PT Slabs',
        "method": "GET",
        "path_template": '/api/admin/payroll/pt-slabs/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 5. PT Slabs
    },
    {
        "name": "get_lwf_configs",
        "action": 'Get LWF Configs',
        "method": "GET",
        "path_template": '/api/admin/payroll/lwf-configs/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 6. LWF Configs (NEW)
    },
    {
        "name": "get_employee_statutory",
        "action": 'Get Employee Statutory',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/statutory',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 7. Employee Statutory Details
    },
    {
        "name": "get_tax_config",
        "action": 'Get Tax Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/tax-config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 8. Tax Config & Declarations
    },
    {
        "name": "get_employee_tax_declaration",
        "action": 'Get Employee Tax Declaration',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/tax-declaration/{financial_year}',
        "resolve_vars": ['employee_uuid', 'financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 8. Tax Config & Declarations
    },
    {
        "name": "get_tax_proof_documents_for_employee",
        "action": 'Get Tax Proof Documents for Employee',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/tax-declaration/{financial_year}/documents',
        "resolve_vars": ['employee_uuid', 'financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 8. Tax Config & Declarations
    },
    {
        "name": "get_tax_windows",
        "action": 'Get Tax Windows',
        "method": "GET",
        "path_template": '/api/admin/payroll/tax-windows/{legal_entity_uuid}/{financial_year}',
        "resolve_vars": ['legal_entity_uuid', 'financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 8. Tax Config & Declarations
    },
    {
        "name": "get_employee_perquisites",
        "action": 'Get Employee Perquisites',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/perquisites/{financial_year}',
        "resolve_vars": ['employee_uuid', 'financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 9. Perquisites (NEW)
    },
    {
        "name": "get_calendars_by_year_optional",
        "action": 'Get Calendars (by year, optional)',
        "method": "GET",
        "path_template": '/api/admin/payroll/calendars/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 10. Payroll Calendar
    },
    {
        "name": "get_run",
        "action": 'Get Run',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 11. Payroll Runs
    },
    {
        "name": "list_variable_inputs_for_run",
        "action": 'List Variable Inputs for Run',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/variable-inputs',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 12. Variable Inputs
    },
    {
        "name": "list_employees_in_run",
        "action": 'List Employees in Run',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/employees',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 13. Employee Payroll (per Run)
    },
    {
        "name": "get_employee_payroll_in_run",
        "action": 'Get Employee Payroll in Run',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/employees/{employee_uuid}',
        "resolve_vars": ['run_uuid', 'employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 13. Employee Payroll (per Run)
    },
    {
        "name": "payroll_register",
        "action": 'Payroll Register',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/register',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 14. Reports
    },
    {
        "name": "bank_export_csv",
        "action": 'Bank Export (CSV)',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/bank-export',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 14. Reports
    },
    {
        "name": "statutory_register",
        "action": 'Statutory Register',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/statutory-register',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 14. Reports
    },
    {
        "name": "list_employee_loans",
        "action": 'List Employee Loans',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/loans',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 15. Loans & Advances
    },
    {
        "name": "list_employee_fnf_settlements",
        "action": 'List Employee FnF Settlements',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/fnf',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 16. Full & Final Settlement
    },
    {
        "name": "get_my_payslip",
        "action": 'Get My Payslip',
        "method": "GET",
        "path_template": '/api/hr/payslips/{payslip_uuid}',
        "resolve_vars": ['payslip_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2500,
        # source: Payroll / 17. Payslips (Employee Self-Service)
    },
    {
        "name": "get_my_declaration",
        "action": 'Get My Declaration',
        "method": "GET",
        "path_template": '/api/hr/tax-declaration/{financial_year}',
        "resolve_vars": ['financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 18. Tax Declaration (Employee Self-Service, NEW)
    },
    {
        "name": "get_my_proof_documents",
        "action": 'Get My Proof Documents',
        "method": "GET",
        "path_template": '/api/hr/tax-declaration/{financial_year}/documents',
        "resolve_vars": ['financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 18. Tax Declaration (Employee Self-Service, NEW)
    },
    {
        "name": "direct_reports_depth_1",
        "action": 'Direct Reports (Depth 1)',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/direct-reports',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "full_team_all_depths",
        "action": 'Full Team (All Depths)',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/team',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "reporting_chain_upward",
        "action": 'Reporting Chain (Upward)',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/reporting-chain',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "managers_by_level_direct_l2_l3",
        "action": 'Managers By Level (Direct / L2 / L3)',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/managers',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "manager_history",
        "action": 'Manager History',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/manager-history',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "team_member_profile",
        "action": 'Team Member Profile',
        "method": "GET",
        "path_template": '/api/me/team/roster/{member_uuid}',
        "resolve_vars": ['member_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Manager Self Service / 1. Dashboard & Roster
    },
    {
        "name": "get_event_detail_rules_templates",
        "action": 'Get Event Detail (Rules + Templates)',
        "method": "GET",
        "path_template": '/api/admin/notifications/events/{event_uuid}',
        "resolve_vars": ['event_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Notifications / 1. Admin — Events
    },
]