"""
Central registry of endpoints monitored by the daily API Health Suite.

v8: adds 4 new endpoints (see "NEW IN v8" below), fixes the financial_year
resolver to return a UUID instead of a human-readable fy_code (backend
expects a UUID -- this was the root cause of 5 pre-existing tax-endpoint
failures), and scaffolds AUTH_PROFILES for HR/Admin/Finance role-based
testing.

IMPORTANT -- CURRENT STATE OF ROLE-BASED TESTING:
As of this version, the credential in use (HEALTH_USER_USERNAME /
HEALTH_USER_PASSWORD) has access across ALL roles, so every endpoint
below still uses "employee" as its auth_profile. The hr/admin/finance
profiles are scaffolded below (env var names reserved) but NOT YET
assigned to endpoints, because doing so with a shared super-account
would not actually test role boundaries -- it would just be cosmetic.

Once real role-scoped credentials are issued:
  1. Set HEALTH_HR_USERNAME / HEALTH_HR_PASSWORD (and admin/finance
     equivalents) as GitHub secrets + workflow env vars.
  2. Go through ENDPOINTS below and reassign "auth_profile" per endpoint
     to whichever role actually owns/uses that API in production
     (e.g. /api/admin/payroll/* -> "finance" or "admin",
     /api/hr/* management endpoints -> "hr", /api/me/* -> "employee").
  3. Only then will failures here reflect real "can an HR/Admin/Finance
     user do their job" answers -- which is the whole point of this
     suite ahead of client-facing use.

v7: expanded from the INJIN HRMS Postman collection (421 total requests
reviewed). Three groups below:
  1. ORIGINAL 10 -- the hand-built starting set (unchanged)
  2. CLEAN ADDITIONS -- safe GET reads, no dynamic ID needed
  3. RESOLVABLE ADDITIONS -- need a real record ID first; resolved at
     runtime by calling a 'source' list endpoint and extracting an ID
     (see RESOLVER_CONFIG and utils/health_id_resolver.py)

38 endpoints from the Postman collection are DELIBERATELY EXCLUDED --
see postman_excluded_needs_review.xlsx for the list and why each needs
your input before it can be added safely.
"""

from datetime import date


def current_month_param():
    return {"month": date.today().strftime("%Y-%m")}


def leave_requests_params():
    return {"page": 1, "per_page": 10, "order": "desc"}


def tickets_params():
    return {"page": 1, "per_page": 10}


def notifications_params():
    return {"page": 1, "per_page": 10, "unread_only": "false"}


# ---------------------------------------------------------------------------
# AUTH_PROFILES: one entry per distinct role that can log in.
#
# "employee" is the only profile currently backed by real, distinct
# credentials -- see module docstring above. hr/admin/finance are
# scaffolded so they're ready to activate the moment role-scoped
# credentials are issued; until then, do NOT assign endpoints to them,
# since the underlying account is identical to "employee" today and
# would give a false sense of role-based coverage.
# ---------------------------------------------------------------------------
AUTH_PROFILES = {
    "employee": {
        "username_env": "HEALTH_USER_USERNAME",
        "password_env": "HEALTH_USER_PASSWORD",
    },
    "hr": {
        "username_env": "HEALTH_HR_USERNAME",
        "password_env": "HEALTH_HR_PASSWORD",
    },
    "admin": {
        "username_env": "HEALTH_ADMIN_USERNAME",
        "password_env": "HEALTH_ADMIN_PASSWORD",
    },
    "finance": {
        "username_env": "HEALTH_FINANCE_USERNAME",
        "password_env": "HEALTH_FINANCE_PASSWORD",
    },
}

DEFAULT_SLA_MS = 2000

# ---------------------------------------------------------------------------
# RESOLVER_CONFIG: for RESOLVABLE ADDITIONS below. Each key is a path
# variable name; 'source_path' is a GET endpoint (already in this registry)
# that returns a list -- we take the FIRST item and try each field name in
# 'fields' (in order) until one exists in that item, and use its value.
#
# IMPORTANT: 'fields' are best-guess field names. After your first real run,
# check the health report / logs for any 'ID resolution failed' errors and
# adjust the field name list to match your API's actual response shape.
# ---------------------------------------------------------------------------
RESOLVER_CONFIG = {
    "announcement_uuid": {
        "source_path": "/api/hr/announcements",
        "fields": [
            "announcement_uuid",
            "uuid",
            "id"
        ]
    },
    "employee_uuid": {
        "source_path": "/api/hr/users",
        "fields": [
            "employee_uuid",
            "uuid",
            "id"
        ]
    },
    "event_uuid": {
        "source_path": "/api/admin/notifications/events",
        "fields": [
            "event_uuid",
            "uuid",
            "id"
        ]
    },
    "financial_year": {
        # FIX (v8): backend expects a UUID for this path variable, not the
        # human-readable fy_code (e.g. "2027-28") -- that was causing
        # "invalid input syntax for type uuid" 500s on every tax-related
        # endpoint that resolves financial_year. uuid now tried first.
        "source_path": "/api/admin/financial-years",
        "fields": ["uuid", "id", "fy_code"],
    },
    "legal_entity_uuid": {
        "source_path": "/api/admin/legal-entities",
        "fields": [
            "legal_entity_uuid",
            "uuid",
            "id"
        ]
    },
    "payslip_uuid": {
        "source_path": "/api/hr/payslips",
        "fields": [
            "payslip_uuid",
            "uuid",
            "id"
        ]
    },
    "run_uuid": {
        "source_path": "/api/admin/payroll/runs",
        "fields": [
            "run_uuid",
            "uuid",
            "id"
        ]
    },
    "member_uuid": {
        "source_path": "/api/me/team/roster",
        "fields": [
            "member_uuid",
            "employee_uuid",
            "uuid",
            "id"
        ]
    }
}


ENDPOINTS = [
    # =========================================================================
    # ORIGINAL 10 -- hand-built starting set
    # =========================================================================
    {
        "name": "login",
        "module": "Authentication",
        "submodule": "Login",
        "action": "User Login / Authentication",
        "method": "POST",
        "path": "/api/auth/login",
        "is_login": True,
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1500,
    },
    {
        "name": "me",
        "module": "Employee Self-Service",
        "submodule": "Profile",
        "action": "Fetch Logged-in User Profile",
        "method": "GET",
        "path": "/api/me",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1000,
    },
    {
        "name": "get_user_details",
        "module": "Employee Self-Service",
        "submodule": "Profile",
        "action": "Fetch Extended User Details",
        "method": "GET",
        "path": "/api/me/getUserDetails",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1000,
    },
    {
        "name": "employee_leave_policy",
        "module": "Employee Self-Service",
        "submodule": "Leave",
        "action": "Fetch Leave Policy",
        "method": "GET",
        "path": "/api/me/employee-leave-policy",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "employee_holiday_policy",
        "module": "Employee Self-Service",
        "submodule": "Leave",
        "action": "Fetch Holiday Policy",
        "method": "GET",
        "path": "/api/me/employee-holiday-policy",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "attendance_monthly",
        "module": "Employee Self-Service",
        "submodule": "Attendance",
        "action": "Fetch Monthly Attendance",
        "method": "GET",
        "path": "/api/me/attendance",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        "params": current_month_param,
    },
    {
        "name": "leave_requests",
        "module": "Employee Self-Service",
        "submodule": "Leave",
        "action": "Fetch Leave Requests",
        "method": "GET",
        "path": "/api/me/leave-requests",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        "params": leave_requests_params,
    },
    {
        "name": "ticketing_tickets",
        "module": "Ticketing",
        "submodule": "My Tickets",
        "action": "Fetch Support Tickets",
        "method": "GET",
        "path": "/api/me/ticketing/tickets",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        "params": tickets_params,
    },
    {
        "name": "notifications",
        "module": "Employee Self-Service",
        "submodule": "Notifications",
        "action": "Fetch Notifications",
        "method": "GET",
        "path": "/api/me/notifications",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        "params": notifications_params,
    },
    {
        "name": "hr_payslips",
        "module": "Employee Self-Service",
        "submodule": "Payslips",
        "action": "Fetch Payslips",
        "method": "GET",
        "path": "/api/hr/payslips",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
    },
    # =========================================================================
    # CLEAN ADDITIONS from Postman collection (108 endpoints)
    # Safe GET reads, no dynamic ID needed, auth normalized to 'employee'
    # since your account has access across employee/hr/admin scopes.
    # =========================================================================
    {
        "name": "login_pm",
        "module": "Authentication",
        "submodule": "Login",
        "action": 'User Login / Authentication',
        "method": "POST",
        "path": '/api/auth/login',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1500,
    },
    {
        "name": "me_pm",
        "module": "Employee Self-Service",
        "submodule": "Profile",
        "action": 'Fetch Logged-in User Profile',
        "method": "GET",
        "path": '/api/me',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1000,
    },
    {
        "name": "get_user_details_pm",
        "module": "Employee Self-Service",
        "submodule": "Profile",
        "action": 'Fetch Extended User Details',
        "method": "GET",
        "path": '/api/me/getUserDetails',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1000,
    },
    {
        "name": "employee_leave_policy_pm",
        "module": "Employee Self-Service",
        "submodule": "Leave",
        "action": 'Fetch Leave Policy',
        "method": "GET",
        "path": '/api/me/employee-leave-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "employee_holiday_policy_pm",
        "module": "Employee Self-Service",
        "submodule": "Leave",
        "action": 'Fetch Holiday Policy',
        "method": "GET",
        "path": '/api/me/employee-holiday-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "attendance_monthly_pm",
        "module": "Employee Self-Service",
        "submodule": "Attendance",
        "action": 'Fetch Monthly Attendance',
        "method": "GET",
        "path": '/api/me/attendance',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "leave_requests_pm",
        "module": "Employee Self-Service",
        "submodule": "Leave",
        "action": 'Fetch Leave Requests',
        "method": "GET",
        "path": '/api/me/leave-requests',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "ticketing_tickets_pm",
        "module": "Ticketing",
        "submodule": "My Tickets",
        "action": 'Fetch Support Tickets',
        "method": "GET",
        "path": '/api/me/ticketing/tickets',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "notifications_pm",
        "module": "Employee Self-Service",
        "submodule": "Notifications",
        "action": 'Fetch Notifications',
        "method": "GET",
        "path": '/api/me/notifications',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "hr_payslips_pm",
        "module": "Employee Self-Service",
        "submodule": "Payslips",
        "action": 'Fetch Payslips',
        "method": "GET",
        "path": '/api/hr/payslips',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
    },
    {
        "name": "fetch_ticket_types",
        "module": "Ticketing",
        "submodule": "Ticket Types",
        "action": 'Fetch Ticket Types',
        "method": "GET",
        "path": '/admin/ticketing/ticket-types',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_invite_list",
        "module": "HR Management",
        "submodule": "Onboarding",
        "action": 'Fetch Invite List',
        "method": "GET",
        "path": '/api/hr/offers',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "onboarding_approved",
        "module": "HR Management",
        "submodule": "Onboarding",
        "action": 'Onboarding Approved',
        "method": "GET",
        "path": '/api/hr/onboarding-approved',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_users_list",
        "module": "HR Management",
        "submodule": "Users",
        "action": 'Fetch Users List',
        "method": "GET",
        "path": '/api/hr/users',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_user_detail_by_user",
        "module": "Employee Self-Service",
        "submodule": "Profile",
        "action": 'Fetch User Detail By User',
        "method": "GET",
        "path": '/api/me/users',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_attendance_summary",
        "module": "HR Management",
        "submodule": "Attendance",
        "action": 'Fetch Attendance Summary',
        "method": "GET",
        "path": '/api/hr/attendance/',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_full_manager_list",
        "module": "HR Management",
        "submodule": "Users",
        "action": 'Fetch Full Manager List',
        "method": "GET",
        "path": '/api/hr/users/managers-list',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "metrics",
        "module": "HR Management",
        "submodule": "Dashboard",
        "action": 'Metrics',
        "method": "GET",
        "path": '/api/hr/dashboard/metrics',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "workforce_snapshot",
        "module": "HR Management",
        "submodule": "Dashboard",
        "action": 'Workforce Snapshot',
        "method": "GET",
        "path": '/api/hr/dashboard/workforce-snapshot',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "attendance_overview",
        "module": "HR Management",
        "submodule": "Dashboard",
        "action": 'Attendance Overview',
        "method": "GET",
        "path": '/api/hr/dashboard/attendance-overview',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "pending_approvals",
        "module": "HR Management",
        "submodule": "Dashboard",
        "action": 'Pending Approvals',
        "method": "GET",
        "path": '/api/hr/dashboard/pending-approvals',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "recent_joiners",
        "module": "HR Management",
        "submodule": "Dashboard",
        "action": 'Recent Joiners',
        "method": "GET",
        "path": '/api/hr/dashboard/recent-joiners',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "today_onboarding",
        "module": "HR Management",
        "submodule": "Dashboard",
        "action": 'Today Onboarding',
        "method": "GET",
        "path": '/api/hr/dashboard/today-onboarding',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "celebrations",
        "module": "HR Management",
        "submodule": "Dashboard",
        "action": 'Celebrations',
        "method": "GET",
        "path": '/api/hr/dashboard/celebrations',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "list_announcements_hr_admin",
        "module": "HR Management",
        "submodule": "Announcements",
        "action": 'List Announcements (HR admin)',
        "method": "GET",
        "path": '/api/hr/announcements',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "my_announcements_feed_employee",
        "module": "Employee Self-Service",
        "submodule": "Announcements",
        "action": 'My Announcements Feed (Employee)',
        "method": "GET",
        "path": '/api/me/announcements',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "list_templates",
        "module": "HR Management",
        "submodule": "Announcements",
        "action": 'List Templates',
        "method": "GET",
        "path": '/api/hr/announcement-templates',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "self_permissions",
        "module": "Employee Self-Service",
        "submodule": "Profile",
        "action": 'Self Permissions',
        "method": "GET",
        "path": '/api/me/permissions',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_user_attendance_config",
        "module": "Employee Self-Service",
        "submodule": "Attendance",
        "action": 'Fetch User Attendance Config',
        "method": "GET",
        "path": '/api/me/attendance-config',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_hr_level_employee_leave_policy",
        "module": "HR Management",
        "submodule": "Leave",
        "action": 'Fetch Hr Level Employee Leave Policy',
        "method": "GET",
        "path": '/api/hr/hr-employee-leave-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_all_employee_applied_leave",
        "module": "Employee Self-Service",
        "submodule": "Leave",
        "action": 'Fetch All Employee Applied Leave',
        "method": "GET",
        "path": '/api/me/fetch-all-applied-leave',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_hr_level_applied_leave",
        "module": "HR Management",
        "submodule": "Leave",
        "action": 'Fetch Hr Level Applied Leave',
        "method": "GET",
        "path": '/api/hr/fetch-all-applied-leave',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_tickets",
        "module": "Ticketing",
        "submodule": "Tickets",
        "action": 'Fetch Tickets',
        "method": "GET",
        "path": '/api/ticketing/tickets',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "upcoming_events",
        "module": "Employee Self-Service",
        "submodule": "Dashboard",
        "action": 'Upcoming Events',
        "method": "GET",
        "path": '/api/me/dashboard/upcoming-events',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_pending_tickets",
        "module": "Ticketing",
        "submodule": "Pending Approvals",
        "action": 'Fetch Pending Tickets',
        "method": "GET",
        "path": '/api/ticketing/pending-approvals',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "my_team_manager_direct_reports",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'My Team (Manager + Direct Reports)',
        "method": "GET",
        "path": '/api/me/team',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "organisation_chart_flat_list",
        "module": "Employee Self-Service",
        "submodule": "Org Chart",
        "action": 'Organisation Chart (Flat List)',
        "method": "GET",
        "path": '/api/me/organisation',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "organisation_chart_nested_tree",
        "module": "Employee Self-Service",
        "submodule": "Org Chart",
        "action": 'Organisation Chart (Nested Tree)',
        "method": "GET",
        "path": '/api/me/organisation/tree',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "team_dashboard",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Team Dashboard',
        "method": "GET",
        "path": '/api/me/team/dashboard',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "team_roster_full_subtree",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Team Roster (Full Subtree)',
        "method": "GET",
        "path": '/api/me/team/roster',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "pending_leave_requests_mine_to_approve",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Pending Leave Requests (Mine to Approve)',
        "method": "GET",
        "path": '/api/me/team/leave-requests',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "team_leave_calendar_month_subtree",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Team Leave Calendar (Month, Subtree)',
        "method": "GET",
        "path": '/api/me/team/leave-calendar',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "team_leave_balance",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Team Leave Balance',
        "method": "GET",
        "path": '/api/me/team/leave-balance',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "team_attendance_calendar_month_subtree",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Team Attendance Calendar (Month, Subtree)',
        "method": "GET",
        "path": '/api/me/team/attendance',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "team_attendance_today",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Team Attendance -- Today',
        "method": "GET",
        "path": '/api/me/team/attendance/today',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "unified_pending_approvals",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Unified Pending Approvals',
        "method": "GET",
        "path": '/api/me/team/approvals',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "get_unread_count",
        "module": "Employee Self-Service",
        "submodule": "Notifications",
        "action": 'Get Unread Count',
        "method": "GET",
        "path": '/api/me/notifications/unread-count',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "get_my_mute_preferences",
        "module": "Employee Self-Service",
        "submodule": "Notifications",
        "action": 'Get My Mute Preferences',
        "method": "GET",
        "path": '/api/me/notification-preferences',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_permissions",
        "module": "RBAC & Settings",
        "submodule": "Permissions",
        "action": 'Fetch Permissions',
        "method": "GET",
        "path": '/api/admin/permissions/matrix',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: RBAC
    },
    {
        "name": "fetch_roles",
        "module": "RBAC & Settings",
        "submodule": "Roles",
        "action": 'Fetch Roles',
        "method": "GET",
        "path": '/api/admin/roles',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: RBAC
    },
    {
        "name": "fetch_attendance_default_list",
        "module": "Master Data",
        "submodule": "Attendance Default",
        "action": 'Fetch Attendance Default List',
        "method": "GET",
        "path": '/api/admin/attendance-defaults',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Master Data / Attendance Default
    },
    {
        "name": "fetch_attendance_default",
        "module": "Master Data",
        "submodule": "Attendance Default",
        "action": 'Fetch Attendance Default',
        "method": "GET",
        "path": '/api/admin/attendance-defaults/current',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Master Data / Attendance Default
    },
    {
        "name": "fetch_master_option_list",
        "module": "Master Data",
        "submodule": "Master Options",
        "action": 'Fetch Master Option List',
        "method": "GET",
        "path": '/api/admin/master-options/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Master Options
    },
    {
        "name": "fetch_master_option_dependent_list",
        "module": "Master Data",
        "submodule": "Master Options",
        "action": 'Fetch Master Option Dependent List',
        "method": "GET",
        "path": '/api/admin/master-options/mode_type',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Master Options
    },
    {
        "name": "fetch_ip_address_list",
        "module": "Master Data",
        "submodule": "IP Address",
        "action": 'Fetch IP Address List',
        "method": "GET",
        "path": '/api/admin/ip-addresses',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / IP Address
    },
    {
        "name": "fetch_attendance_source_list",
        "module": "Master Data",
        "submodule": "Attendance Source",
        "action": 'Fetch  Attendance Source List',
        "method": "GET",
        "path": '/api/admin/attendance-source',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Master Data / Attendance Source
    },
    {
        "name": "fetch_work_mode_list",
        "module": "Master Data",
        "submodule": "Work Mode",
        "action": 'Fetch  Work Mode List',
        "method": "GET",
        "path": '/api/admin/work-mode',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Work Mode
    },
    {
        "name": "fetch_attendance_policy_list",
        "module": "Master Data",
        "submodule": "Attendance Policy",
        "action": 'Fetch  Attendance Policy List',
        "method": "GET",
        "path": '/api/admin/attendance-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Master Data / Attendance Policy
    },
    {
        "name": "fetch_break_policy_list",
        "module": "Master Data",
        "submodule": "Break Policy",
        "action": 'Fetch  Break Policy List',
        "method": "GET",
        "path": '/api/admin/break-policy',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Break Policy
    },
    {
        "name": "fetch_shift_list",
        "module": "Master Data",
        "submodule": "Shifts",
        "action": 'Fetch Shift List',
        "method": "GET",
        "path": '/api/admin/shifts',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Shift
    },
    {
        "name": "fetch_salary_structure_list",
        "module": "Master Data",
        "submodule": "Salary Structure",
        "action": 'Fetch Salary Structure List',
        "method": "GET",
        "path": '/api/admin/salary-structures',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Master Data / Salary Structure
    },
    {
        "name": "salary_structure_meta",
        "module": "Master Data",
        "submodule": "Salary Structure",
        "action": 'Salary Structure Meta',
        "method": "GET",
        "path": '/api/admin/salary-structures/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Master Data / Salary Structure
    },
    {
        "name": "fetch_pay_component_group_list",
        "module": "Master Data",
        "submodule": "Pay Component Group",
        "action": 'Fetch Pay Component Group List',
        "method": "GET",
        "path": '/api/admin/pay-component-groups',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Component Group
    },
    {
        "name": "pay_component_group_meta",
        "module": "Master Data",
        "submodule": "Pay Component Group",
        "action": 'Pay Component Group Meta',
        "method": "GET",
        "path": '/api/admin/pay-component-groups/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Component Group
    },
    {
        "name": "fetch_pay_component_rule_list",
        "module": "Master Data",
        "submodule": "Pay Component Rules",
        "action": 'Fetch Pay Component Rule List',
        "method": "GET",
        "path": '/api/admin/pay-component-rules',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Components Rule
    },
    {
        "name": "pay_component_rule_meta",
        "module": "Master Data",
        "submodule": "Pay Component Rules",
        "action": 'Pay Component Rule Meta',
        "method": "GET",
        "path": '/api/admin/pay-component-rules/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Components Rule
    },
    {
        "name": "fetch_pay_component_list",
        "module": "Master Data",
        "submodule": "Pay Components",
        "action": 'Fetch Pay Component List',
        "method": "GET",
        "path": '/api/admin/pay-components',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Component
    },
    {
        "name": "pay_component_meta",
        "module": "Master Data",
        "submodule": "Pay Components",
        "action": 'Pay Component Meta',
        "method": "GET",
        "path": '/api/admin/pay-components/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Component
    },
    {
        "name": "fetch_pay_range_list",
        "module": "Master Data",
        "submodule": "Pay Range",
        "action": 'Fetch Pay Range List',
        "method": "GET",
        "path": '/api/admin/pay-ranges',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Range
    },
    {
        "name": "fetch_cost_center_list",
        "module": "Master Data",
        "submodule": "Cost Center",
        "action": 'Fetch Cost Center List',
        "method": "GET",
        "path": '/api/admin/cost-centers',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Cost Center
    },
    {
        "name": "fetch_job_title_list",
        "module": "Master Data",
        "submodule": "Job Title",
        "action": 'Fetch Job Title List',
        "method": "GET",
        "path": '/api/admin/job-titles',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Job Title
    },
    {
        "name": "fetch_sub_function_list",
        "module": "Master Data",
        "submodule": "Sub Function",
        "action": 'Fetch Sub Function List',
        "method": "GET",
        "path": '/api/admin/sub-functions',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Sub Function
    },
    {
        "name": "fetch_function_list",
        "module": "Master Data",
        "submodule": "Function",
        "action": 'Fetch Function List',
        "method": "GET",
        "path": '/api/admin/functions',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Function
    },
    {
        "name": "fetch_pay_grade_list",
        "module": "Master Data",
        "submodule": "Pay Grade",
        "action": 'Fetch Pay Grade List',
        "method": "GET",
        "path": '/api/admin/pay-grades',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Pay Grade
    },
    {
        "name": "fetch_work_location_list",
        "module": "Master Data",
        "submodule": "Work Location",
        "action": 'Fetch Work Location List',
        "method": "GET",
        "path": '/api/admin/work-locations',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Work Location
    },
    {
        "name": "fetch_geo_zone_list",
        "module": "Master Data",
        "submodule": "Geo Zones",
        "action": 'Fetch Geo Zone List',
        "method": "GET",
        "path": '/api/admin/geozones',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Geo Zones
    },
    {
        "name": "fetch_employee_leave_approval",
        "module": "Master Data",
        "submodule": "Comp Off Requests",
        "action": 'Fetch Employee Leave Approval',
        "method": "GET",
        "path": '/api/admin/comp-off-requests',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Comp Off Request
    },
    {
        "name": "fetch_optional_holiday",
        "module": "Master Data",
        "submodule": "Optional Holiday",
        "action": 'Fetch Optional Holiday',
        "method": "GET",
        "path": '/api/admin/optional-holiday-selections',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Optional Holiday Selection
    },
    {
        "name": "fetch_employee_leave_approval_2",
        "module": "Master Data",
        "submodule": "Leave Approval Workflow",
        "action": 'Fetch Employee Leave Approval',
        "method": "GET",
        "path": '/api/admin/leave-approval-workflows',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Leave Approval WorkFlow
    },
    {
        "name": "fetch_holiday_group",
        "module": "Master Data",
        "submodule": "Holiday Group",
        "action": 'Fetch Holiday Group',
        "method": "GET",
        "path": '/api/admin/holiday-groups/{uuid}',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Holiday Group
    },
    {
        "name": "fetch_financial_year",
        "module": "Master Data",
        "submodule": "Financial Year",
        "action": 'Fetch Financial Year',
        "method": "GET",
        "path": '/api/admin/financial-years',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Financial Year Master
    },
    {
        "name": "get_active_year",
        "module": "Master Data",
        "submodule": "Financial Year",
        "action": 'Get Active Year',
        "method": "GET",
        "path": '/api/admin/financial-years/active',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Financial Year Master
    },
    {
        "name": "fetch_leave_policy_assignemnt_list",
        "module": "Master Data",
        "submodule": "Leave Balance Ledger",
        "action": 'Fetch Leave Policy Assignemnt List',
        "method": "GET",
        "path": '/api/admin/leave-balance-ledger',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Leave Balance Ledger
    },
    {
        "name": "fetch_leave_group",
        "module": "Master Data",
        "submodule": "Leave Policy Group",
        "action": 'Fetch Leave Group',
        "method": "GET",
        "path": '/api/admin/policy-groups',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Leave Policy Group
    },
    {
        "name": "show_by_code",
        "module": "Master Data",
        "submodule": "Leave Types",
        "action": 'Show By Code',
        "method": "GET",
        "path": '/api/admin/leave-types/code/CL',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Leave Type
    },
    {
        "name": "fetch_legal_entity_list",
        "module": "Master Data",
        "submodule": "Legal Entity",
        "action": 'Fetch Legal Entity List',
        "method": "GET",
        "path": '/api/admin/legal-entities',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Legal Entity
    },
    {
        "name": "fetch_hierarchy_level",
        "module": "Master Data",
        "submodule": "Hierarchy Levels",
        "action": 'Fetch Hierarchy Level',
        "method": "GET",
        "path": '/api/admin/hierarchy-levels/{uuid}',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Hierarchy Levels
    },
    {
        "name": "fetch_workflows",
        "module": "Ticketing",
        "submodule": "Workflows",
        "action": 'Fetch Workflows',
        "method": "GET",
        "path": '/api/admin/ticketing/workflows',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Ticketing / Workflows
    },
    {
        "name": "admin_show_tickets",
        "module": "Ticketing",
        "submodule": "Admin Tickets",
        "action": 'Admin Show Tickets',
        "method": "GET",
        "path": '/api/admin/ticketing/tickets',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Ticketing / Admin Tickets
    },
    {
        "name": "admin_show_tickets_comments",
        "module": "Ticketing",
        "submodule": "Admin Tickets",
        "action": 'Admin Show Tickets Comments',
        "method": "GET",
        "path": '/api/admin/ticketing/tickets/{uuid}/comments',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Ticketing / Admin Tickets
    },
    {
        "name": "cancel_tickets",
        "module": "Ticketing",
        "submodule": "Admin Tickets",
        "action": 'Cancel Tickets',
        "method": "GET",
        "path": '/api/admin/ticketing/tickets/{uuid}/cancel',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Master Data / Ticketing / Admin Tickets
    },
    {
        "name": "fetch_document_list_copy",
        "module": "Onboarding",
        "submodule": "Document Types",
        "action": 'Fetch Document List Copy',
        "method": "GET",
        "path": '/api/onboarding/meta/document-types',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Onboarding
    },
    {
        "name": "fetch_form_schema",
        "module": "Onboarding",
        "submodule": "Form Schema",
        "action": 'Fetch Form Schema',
        "method": "GET",
        "path": '/api/onboarding/meta/form-schema',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Onboarding
    },
    {
        "name": "fetch_meta_data",
        "module": "Onboarding",
        "submodule": "Meta",
        "action": 'Fetch Meta Data',
        "method": "GET",
        "path": '/api/onboarding/meta',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Onboarding
    },
    {
        "name": "fetch_employee_attendance_policy_history",
        "module": "HR Management",
        "submodule": "Attendance",
        "action": 'Fetch Employee Attendance Policy History',
        "method": "GET",
        "path": '/api/hr/employees/{uuid}/attendance-config/history',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Human Resources / Attendance
    },
    {
        "name": "fetch_employee_attendance_day_override",
        "module": "HR Management",
        "submodule": "Attendance",
        "action": 'Fetch Employee Attendance Day Override',
        "method": "GET",
        "path": '/api/hr/employees/{employeeUuid}/attendance-override/2026-05-12',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
        # source: Human Resources / Attendance
    },
    {
        "name": "fetch_direct_reportees",
        "module": "HR Management",
        "submodule": "Reporting Manager",
        "action": 'Fetch Direct Reportees',
        "method": "GET",
        "path": '/api/hr/users/{uuid}/direct-reports',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Reporting Manager
    },
    {
        "name": "fetch_reporting_team",
        "module": "HR Management",
        "submodule": "Reporting Manager",
        "action": 'Fetch Reporting Team',
        "method": "GET",
        "path": '/api/hr/users/{uuid}/team',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Reporting Manager
    },
    {
        "name": "fetch_reporting_chain",
        "module": "HR Management",
        "submodule": "Reporting Manager",
        "action": 'Fetch Reporting Chain',
        "method": "GET",
        "path": '/api/hr/users/{uuid}/reporting-chain',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Reporting Manager
    },
    {
        "name": "fetch_employee_group",
        "module": "HR Management",
        "submodule": "Holiday",
        "action": 'Fetch Employee Group',
        "method": "GET",
        "path": '/api/hr/employee-holiday-group-assignments/{uuid}',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Human Resources / Holiday
    },
    {
        "name": "fetch_employee_week_off",
        "module": "HR Management",
        "submodule": "Weekly Off",
        "action": 'Fetch Employee Week Off',
        "method": "GET",
        "path": '/api/hr/employee-weekly-off-assignment/{uuid}',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Weekly Off
    },
    {
        "name": "fetch_employee_code_setting",
        "module": "RBAC & Settings",
        "submodule": "Employee Code",
        "action": 'Fetch Employee Code Setting',
        "method": "GET",
        "path": '/api/admin/settings/employee-code',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: HRMS Settings / Employee Code
    },
    {
        "name": "fetch_app_timezone",
        "module": "RBAC & Settings",
        "submodule": "Timezone",
        "action": 'Fetch App Timezone',
        "method": "GET",
        "path": '/api/admin/settings/timezone',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: HRMS Settings / Timezone
    },
    {
        "name": "fetch_ui_color",
        "module": "RBAC & Settings",
        "submodule": "UI Color",
        "action": 'Fetch UI Color',
        "method": "GET",
        "path": '/api/admin/settings/ui-color',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: HRMS Settings / UI Color
    },
    {
        "name": "fetch_probation_notice",
        "module": "RBAC & Settings",
        "submodule": "HR Defaults",
        "action": 'Fetch Probation & Notice',
        "method": "GET",
        "path": '/api/admin/settings/hr-defaults',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: HRMS Settings / Probation & Notice
    },
    {
        "name": "list_runs",
        "module": "Payroll",
        "submodule": "Payroll Runs",
        "action": 'List Runs',
        "method": "GET",
        "path": '/api/admin/payroll/runs',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 11. Payroll Runs
    },
    {
        "name": "list_all_events",
        "module": "Notifications",
        "submodule": "Events",
        "action": 'List All Events',
        "method": "GET",
        "path": '/api/admin/notifications/events',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Notifications / 1. Admin -- Events
    },
    {
        "name": "list_delivery_logs_no_filters",
        "module": "Notifications",
        "submodule": "Delivery Logs",
        "action": 'List Delivery Logs (no filters)',
        "method": "GET",
        "path": '/api/admin/notifications/logs',
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Notifications / 4. Admin -- Delivery Logs
    },
    # =========================================================================
    # RESOLVABLE ADDITIONS (34 endpoints)
    # path_template uses {var} placeholders, filled in at runtime by
    # utils/health_id_resolver.py using RESOLVER_CONFIG above.
    # =========================================================================
    {
        "name": "get_announcement_by_uuid",
        "module": "HR Management",
        "submodule": "Announcements",
        "action": 'Get Announcement by UUID',
        "method": "GET",
        "path_template": '/api/hr/announcements/{announcement_uuid}',
        "resolve_vars": ['announcement_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Announcements & Events
    },
    {
        "name": "get_config_history",
        "module": "Payroll",
        "submodule": "Config",
        "action": 'Get Config History',
        "method": "GET",
        "path_template": '/api/admin/payroll/config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 1. Payroll Config
    },
    {
        "name": "get_current_config",
        "module": "Payroll",
        "submodule": "Config",
        "action": 'Get Current Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/config/{legal_entity_uuid}/current',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 1. Payroll Config
    },
    {
        "name": "get_pf_config",
        "module": "Payroll",
        "submodule": "PF Config",
        "action": 'Get PF Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/pf-config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 2. PF Config
    },
    {
        "name": "get_gratuity_config",
        "module": "Payroll",
        "submodule": "Gratuity Config",
        "action": 'Get Gratuity Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/gratuity-config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 3. Gratuity Config (NEW)
    },
    {
        "name": "get_esi_config",
        "module": "Payroll",
        "submodule": "ESI Config",
        "action": 'Get ESI Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/esi-config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 4. ESI Config
    },
    {
        "name": "get_pt_slabs",
        "module": "Payroll",
        "submodule": "PT Slabs",
        "action": 'Get PT Slabs',
        "method": "GET",
        "path_template": '/api/admin/payroll/pt-slabs/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 5. PT Slabs
    },
    {
        "name": "get_lwf_configs",
        "module": "Payroll",
        "submodule": "LWF Config",
        "action": 'Get LWF Configs',
        "method": "GET",
        "path_template": '/api/admin/payroll/lwf-configs/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 6. LWF Configs (NEW)
    },
    {
        "name": "get_employee_statutory",
        "module": "Payroll",
        "submodule": "Employee Statutory",
        "action": 'Get Employee Statutory',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/statutory',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 7. Employee Statutory Details
    },
    {
        "name": "get_tax_config",
        "module": "Payroll",
        "submodule": "Tax Config",
        "action": 'Get Tax Config',
        "method": "GET",
        "path_template": '/api/admin/payroll/tax-config/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 8. Tax Config & Declarations
    },
    {
        "name": "get_employee_tax_declaration",
        "module": "Payroll",
        "submodule": "Tax Declaration",
        "action": 'Get Employee Tax Declaration',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/tax-declaration/{financial_year}',
        "resolve_vars": ['employee_uuid', 'financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 8. Tax Config & Declarations
    },
    {
        "name": "get_tax_proof_documents_for_employee",
        "module": "Payroll",
        "submodule": "Tax Declaration",
        "action": 'Get Tax Proof Documents for Employee',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/tax-declaration/{financial_year}/documents',
        "resolve_vars": ['employee_uuid', 'financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 8. Tax Config & Declarations
    },
    {
        "name": "get_tax_windows",
        "module": "Payroll",
        "submodule": "Tax Config",
        "action": 'Get Tax Windows',
        "method": "GET",
        "path_template": '/api/admin/payroll/tax-windows/{legal_entity_uuid}/{financial_year}',
        "resolve_vars": ['legal_entity_uuid', 'financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 8. Tax Config & Declarations
    },
    {
        "name": "get_employee_perquisites",
        "module": "Payroll",
        "submodule": "Perquisites",
        "action": 'Get Employee Perquisites',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/perquisites/{financial_year}',
        "resolve_vars": ['employee_uuid', 'financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 9. Perquisites (NEW)
    },
    {
        "name": "get_calendars_by_year_optional",
        "module": "Payroll",
        "submodule": "Payroll Calendar",
        "action": 'Get Calendars (by year, optional)',
        "method": "GET",
        "path_template": '/api/admin/payroll/calendars/{legal_entity_uuid}',
        "resolve_vars": ['legal_entity_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 10. Payroll Calendar
    },
    {
        "name": "get_run",
        "module": "Payroll",
        "submodule": "Payroll Runs",
        "action": 'Get Run',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 11. Payroll Runs
    },
    {
        "name": "list_variable_inputs_for_run",
        "module": "Payroll",
        "submodule": "Variable Inputs",
        "action": 'List Variable Inputs for Run',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/variable-inputs',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 12. Variable Inputs
    },
    {
        "name": "list_employees_in_run",
        "module": "Payroll",
        "submodule": "Employee Payroll",
        "action": 'List Employees in Run',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/employees',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 13. Employee Payroll (per Run)
    },
    {
        "name": "get_employee_payroll_in_run",
        "module": "Payroll",
        "submodule": "Employee Payroll",
        "action": 'Get Employee Payroll in Run',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/employees/{employee_uuid}',
        "resolve_vars": ['run_uuid', 'employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 13. Employee Payroll (per Run)
    },
    {
        "name": "payroll_register",
        "module": "Payroll",
        "submodule": "Reports",
        "action": 'Payroll Register',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/register',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 14. Reports
    },
    {
        "name": "bank_export_csv",
        "module": "Payroll",
        "submodule": "Reports",
        "action": 'Bank Export (CSV)',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/bank-export',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 14. Reports
    },
    {
        "name": "statutory_register",
        "module": "Payroll",
        "submodule": "Reports",
        "action": 'Statutory Register',
        "method": "GET",
        "path_template": '/api/admin/payroll/runs/{run_uuid}/statutory-register',
        "resolve_vars": ['run_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2500,
        # source: Payroll / 14. Reports
    },
    {
        "name": "list_employee_loans",
        "module": "Payroll",
        "submodule": "Loans & Advances",
        "action": 'List Employee Loans',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/loans',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 15. Loans & Advances
    },
    {
        "name": "list_employee_fnf_settlements",
        "module": "Payroll",
        "submodule": "Full & Final Settlement",
        "action": 'List Employee FnF Settlements',
        "method": "GET",
        "path_template": '/api/admin/employees/{employee_uuid}/fnf',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 16. Full & Final Settlement
    },
    {
        "name": "get_my_payslip",
        "module": "Payroll",
        "submodule": "Payslips",
        "action": 'Get My Payslip',
        "method": "GET",
        "path_template": '/api/hr/payslips/{payslip_uuid}',
        "resolve_vars": ['payslip_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2500,
        # source: Payroll / 17. Payslips (Employee Self-Service)
    },
    {
        "name": "get_my_declaration",
        "module": "Payroll",
        "submodule": "Tax Declaration",
        "action": 'Get My Declaration',
        "method": "GET",
        "path_template": '/api/hr/tax-declaration/{financial_year}',
        "resolve_vars": ['financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 18. Tax Declaration (Employee Self-Service, NEW)
    },
    {
        "name": "get_my_proof_documents",
        "module": "Payroll",
        "submodule": "Tax Declaration",
        "action": 'Get My Proof Documents',
        "method": "GET",
        "path_template": '/api/hr/tax-declaration/{financial_year}/documents',
        "resolve_vars": ['financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Payroll / 18. Tax Declaration (Employee Self-Service, NEW)
    },
    {
        "name": "direct_reports_depth_1",
        "module": "Org Hierarchy",
        "submodule": "Reporting Hierarchy",
        "action": 'Direct Reports (Depth 1)',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/direct-reports',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "full_team_all_depths",
        "module": "Org Hierarchy",
        "submodule": "Reporting Hierarchy",
        "action": 'Full Team (All Depths)',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/team',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "reporting_chain_upward",
        "module": "Org Hierarchy",
        "submodule": "Reporting Hierarchy",
        "action": 'Reporting Chain (Upward)',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/reporting-chain',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "managers_by_level_direct_l2_l3",
        "module": "Org Hierarchy",
        "submodule": "Reporting Hierarchy",
        "action": 'Managers By Level (Direct / L2 / L3)',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/managers',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "manager_history",
        "module": "Org Hierarchy",
        "submodule": "Reporting Hierarchy",
        "action": 'Manager History',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}/manager-history',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Org Hierarchy / Employee Reporting Hierarchy
    },
    {
        "name": "team_member_profile",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": 'Team Member Profile',
        "method": "GET",
        "path_template": '/api/me/team/roster/{member_uuid}',
        "resolve_vars": ['member_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Manager Self Service / 1. Dashboard & Roster
    },
    {
        "name": "get_event_detail_rules_templates",
        "module": "Notifications",
        "submodule": "Events",
        "action": 'Get Event Detail (Rules + Templates)',
        "method": "GET",
        "path_template": '/api/admin/notifications/events/{event_uuid}',
        "resolve_vars": ['event_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Notifications / 1. Admin -- Events
    },
    # =========================================================================
    # NEW IN v8 -- added from gap analysis against the full 421-request
    # Postman collection. All four reuse resolvers that already exist and
    # are already working (employee_uuid, financial_year), so no new
    # RESOLVER_CONFIG entries were needed.
    # =========================================================================
    {
        "name": "get_user_detail_by_id",
        "module": "HR Management",
        "submodule": "Employees",
        "action": 'Fetch User Detail',
        "method": "GET",
        "path_template": '/api/hr/users/{employee_uuid}',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Employees
    },
    {
        "name": "fetch_employee_attendance_config",
        "module": "HR Management",
        "submodule": "Attendance",
        "action": 'Fetch Employee Attendance Policy',
        "method": "GET",
        "path_template": '/api/hr/employees/{employee_uuid}/attendance-config',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Human Resources / Attendance
    },
    {
        "name": "fetch_employee_detailed_attendance",
        "module": "HR Management",
        "submodule": "Attendance",
        "action": 'Fetch Detailed Attendance',
        "method": "GET",
        "path_template": '/api/hr/employees/{employee_uuid}/attendance',
        "resolve_vars": ['employee_uuid'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
        # source: Human Resources / Attendance
    },
    {
        "name": "get_financial_year_by_id",
        "module": "Master Data",
        "submodule": "Financial Year",
        "action": 'Show Financial Year By UUID',
        "method": "GET",
        "path_template": '/api/admin/financial-years/{financial_year}',
        "resolve_vars": ['financial_year'],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
        # source: Master Data / Financial Year Master
    },

        # ---- User / Team module ----
    {
        "name": "leave_balances",
        "module": "Employee Self-Service",
        "submodule": "Leave",
        "action": "Fetch Leave Balances",
        "method": "GET",
        "path": "/api/me/leave-balances",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "team_users_list",
        "module": "Employee Self-Service",
        "submodule": "Team",
        "action": "Fetch Team Users",
        "method": "GET",
        "path": "/api/me/team/users",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "attendance_today",
        "module": "Employee Self-Service",
        "submodule": "Attendance",
        "action": "Fetch Today's Attendance",
        "method": "GET",
        "path": "/api/me/attendance/today",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 1500,
    },
    {
        "name": "offboarding_case",
        "module": "Offboarding",
        "submodule": "My Offboarding",
        "action": "Fetch Offboarding Case",
        "method": "GET",
        "path": "/api/me/offboarding/case",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "offboarding_exit_survey",
        "module": "Offboarding",
        "submodule": "My Offboarding",
        "action": "Fetch Exit Survey",
        "method": "GET",
        "path": "/api/me/offboarding/exit-survey",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "workflow_pending_approvals",
        "module": "Employee Self-Service",
        "submodule": "Workflow",
        "action": "Fetch Workflow Pending Approvals",
        "method": "GET",
        "path": "/api/me/workflow/pending-approvals",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "offboarding_clearance_queue",
        "module": "Offboarding",
        "submodule": "My Offboarding",
        "action": "Fetch Clearance Queue",
        "method": "GET",
        "path": "/api/me/offboarding/clearance-queue",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },

    # ---- Admin module ----
    {
        "name": "admin_dashboard",
        "module": "RBAC & Settings",
        "submodule": "Dashboard",
        "action": "Fetch Admin Dashboard",
        "method": "GET",
        "path": "/api/admin/dashboard",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": True,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_role_permissions",
        "module": "RBAC & Settings",
        "submodule": "Roles",
        "action": "Fetch Role Permissions",
        "method": "GET",
        "path_template": "/api/admin/roles/{role_uuid}/permissions",
        "resolve_vars": ["role_uuid"],
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_hierarchy_levels_list",
        "module": "Master Data",
        "submodule": "Hierarchy Levels",
        "action": "Fetch Hierarchy Levels List",
        "method": "GET",
        "path": "/api/admin/hierarchy-levels",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_weekly_offs_list",
        "module": "Master Data",
        "submodule": "Weekly Off",
        "action": "Fetch Weekly Offs List",
        "method": "GET",
        "path": "/api/admin/weekly-offs",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_leave_types_list",
        "module": "Master Data",
        "submodule": "Leave Types",
        "action": "Fetch Leave Types List",
        "method": "GET",
        "path": "/api/admin/leave-types",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_leave_policies_list",
        "module": "Master Data",
        "submodule": "Leave Policy",
        "action": "Fetch Leave Policies List",
        "method": "GET",
        "path": "/api/admin/leave-policies",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_holiday_groups_list",
        "module": "Master Data",
        "submodule": "Holiday Group",
        "action": "Fetch Holiday Groups List",
        "method": "GET",
        "path": "/api/admin/holiday-groups",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_leave_defaults",
        "module": "Master Data",
        "submodule": "Leave Defaults",
        "action": "Fetch Leave Defaults",
        "method": "GET",
        "path": "/api/admin/leave-defaults",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_holiday_list",
        "module": "Master Data",
        "submodule": "Holiday",
        "action": "Fetch Holiday List",
        "method": "GET",
        "path": "/api/admin/holiday",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_ticket_types_fixed",
        "module": "Ticketing",
        "submodule": "Ticket Types",
        "action": "Fetch Ticket Types",
        "method": "GET",
        "path": "/api/admin/ticketing/ticket-types",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_workflow_definitions",
        "module": "Ticketing",
        "submodule": "Workflows",
        "action": "Fetch Workflow Definitions",
        "method": "GET",
        "path": "/api/admin/workflows/definitions",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 2000,
    },
    {
        "name": "fetch_clearance_templates",
        "module": "Offboarding",
        "submodule": "Admin Offboarding",
        "action": "Fetch Clearance Templates",
        "method": "GET",
        "path": "/api/admin/offboarding/clearance-templates",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_exit_survey_schema",
        "module": "Offboarding",
        "submodule": "Admin Offboarding",
        "action": "Fetch Exit Survey Schema",
        "method": "GET",
        "path": "/api/admin/offboarding/exit-survey-schema",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_master_option_timezone",
        "module": "RBAC & Settings",
        "submodule": "Timezone",
        "action": "Fetch Master Option Timezone",
        "method": "GET",
        "path": "/api/admin/master-options/timezone",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },

    # ---- HR module ----
    {
        "name": "hr_offboarding_cases",
        "module": "HR Management",
        "submodule": "Offboarding",
        "action": "Fetch Offboarding Cases",
        "method": "GET",
        "path": "/api/hr/offboarding/cases",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_emp_code_strategy",
        "module": "RBAC & Settings",
        "submodule": "Employee Code",
        "action": "Fetch Employee Code Strategy",
        "method": "GET",
        "path": "/api/admin/master-options/emp_code_strategy",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_emp_code_sequence_key",
        "module": "RBAC & Settings",
        "submodule": "Employee Code",
        "action": "Fetch Employee Code Sequence Key",
        "method": "GET",
        "path": "/api/admin/master-options/emp_code_sequence_key",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
    {
        "name": "fetch_emp_code_random_type",
        "module": "RBAC & Settings",
        "submodule": "Employee Code",
        "action": "Fetch Employee Code Random Type",
        "method": "GET",
        "path": "/api/admin/master-options/emp_code_random_type",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },

    # ---- Admin module (2nd batch) ----
    {
        "name": "fetch_master_option_payroll_loan_type",
        "module": "Master Data",
        "submodule": "Master Options",
        "action": "Fetch Master Option Payroll Loan Type",
        "method": "GET",
        "path": "/api/admin/master-options/payroll_loan_type",
        "auth_profile": "employee",
        "expected_status": 200,
        "critical": False,
        "sla_ms": 1500,
    },
]