"""
Fixtures scoped to test/health/*.

v9: fully self-contained automation.

At the end of the run:
    1. Excel + JSON are written to disk
       (useful local artifact/audit trail)

    2. HTML dashboard is generated by the email sender
       and grouped/represented by module.

    3. Health dashboard is emailed directly using Resend/Brevo
       HTTP API — no n8n, no SMTP.

    4. Email failure must never hide API health results.
"""

import os
import time

import pytest
import requests

from api_framework.config.health_endpoints import (
    AUTH_PROFILES,
    RESOLVER_CONFIG,
)

from api_framework.auth.health_token_manager import (
    HealthTokenManager,
    resolve_credentials,
)

from utils.health_reporter import HealthReporter
from utils.health_failure_logger import HealthFailureLogger
from utils.health_id_resolver import HealthIdResolver

from utils.run_manager import get_run_folder

from utils.health_email_notifier import send_health_email


# ============================================================
# BASE URL
# ============================================================

@pytest.fixture(scope="session")
def base_url() -> str:
    """
    Base URL of the application under test.

    Can be overridden through the BASE_URL environment variable.
    """

    url = os.getenv(
        "BASE_URL",
        "https://injin-dev.injtechnologies.com",
    )

    return url.rstrip("/")


# ============================================================
# RUN FOLDER
# ============================================================

@pytest.fixture(scope="session")
def health_run_folder():
    """
    Creates/returns the folder for the current health-check run.
    """

    return get_run_folder()


# ============================================================
# FAILURE LOGGER
# ============================================================

@pytest.fixture(scope="session")
def failure_logger(health_run_folder):
    """
    Stores detailed information about failed APIs.
    """

    return HealthFailureLogger(health_run_folder)


# ============================================================
# HEALTH REPORTER
# ============================================================

@pytest.fixture(scope="session")
def health_reporter(health_run_folder):

    reporter = HealthReporter(health_run_folder)

    # ---------------------------------------------------------
    # TEST EXECUTION
    # ---------------------------------------------------------

    yield reporter

    # ---------------------------------------------------------
    # REPORT GENERATION
    # ---------------------------------------------------------

    try:
        report_path = reporter.write_excel()
        print(f"[health-suite] Excel report written: {report_path}")
    except Exception as e:
        print(f"[health-suite] Excel generation failed: {e}")
        report_path = None

    try:
        summary_path = reporter.write_summary_json()
        print(f"[health-suite] JSON summary written: {summary_path}")
    except Exception as e:
        print(f"[health-suite] JSON generation failed: {e}")
        summary_path = None

    # ---------------------------------------------------------
    # SUMMARY
    # ---------------------------------------------------------

    summary = reporter.summary

    print(
        f"[health-suite] "
        f"{summary['passed']}/"
        f"{summary['total']} passed "
        f"({summary['pass_rate']}%)"
    )

    if summary["critical_failed"]:

        print(
            "[health-suite] "
            f"CRITICAL FAILURES: "
            f"{summary['critical_failed']}"
        )

    if summary["sla_breaches"]:

        print(
            "[health-suite] "
            f"SLA BREACHES: "
            f"{summary['sla_breaches']}"
        )

    # ---------------------------------------------------------
    # RESEND HEALTH DASHBOARD EMAIL
    # ---------------------------------------------------------

    try:

        send_health_email(
            summary=summary,
            results=reporter.results,   
            environment=os.getenv(
                "HEALTH_ENVIRONMENT",
                "Development",
            ),
            report_path=report_path,
            summary_path=summary_path,
        )

        print(
            "[health-suite] "
            "Health dashboard email sent successfully."
        )

    except Exception as e:

        # VERY IMPORTANT:
        #
        # Email failure must NEVER make the health suite
        # appear broken when the actual API results exist.
        #
        print(
            "[health-suite] "
            f"Failed to send health dashboard email: {e}"
        )


# ============================================================
# TOKEN MANAGERS
# ============================================================

@pytest.fixture(scope="session")
def token_managers(base_url):

    """
    Creates one HealthTokenManager for every configured
    authentication profile.

    Example:

        employee
        hr
        admin
        finance

    depending on what is present in AUTH_PROFILES.
    """

    managers = {}

    for profile_name in AUTH_PROFILES:

        managers[profile_name] = HealthTokenManager(
            base_url
        )

    return managers


# ============================================================
# HEALTH CLIENT
# ============================================================

@pytest.fixture(scope="session")
def health_client(
    base_url,
    token_managers,
):

    class HealthClient:

        def request(
            self,
            method: str,
            path: str,
            params: dict = None,
            auth_profile: str = None,
            json_body: dict = None,
        ):

            # -------------------------------------------------
            # BUILD URL
            # -------------------------------------------------

            url = f"{base_url}{path}"

            headers = {}

            # -------------------------------------------------
            # AUTHENTICATION
            # -------------------------------------------------

            if auth_profile:

                profile_cfg = AUTH_PROFILES[
                    auth_profile
                ]

                username, password = resolve_credentials(
                    profile_cfg
                )

                manager = token_managers[
                    auth_profile
                ]

                headers = manager.get_headers(
                    username,
                    password,
                )

            # -------------------------------------------------
            # REQUEST TIMER
            # -------------------------------------------------

            start = time.time()

            # -------------------------------------------------
            # API REQUEST
            # -------------------------------------------------

            resp = requests.request(
                method=method,
                url=url,
                params=params,
                headers=headers,
                json=json_body,
                timeout=20,
            )

            # -------------------------------------------------
            # RESPONSE TIME
            # -------------------------------------------------

            elapsed_ms = round(
                (time.time() - start) * 1000,
                1,
            )

            # -------------------------------------------------
            # RETURN EVERYTHING REQUIRED BY HEALTH TEST
            # -------------------------------------------------

            return (
                resp,
                elapsed_ms,
                url,
                headers,
            )

    return HealthClient()


# ============================================================
# ID RESOLVER
# ============================================================

@pytest.fixture(scope="session")
def id_resolver(
    health_client,
):

    """
    Resolves dynamic IDs required by APIs.

    Example:

        employee ID
        holiday group UUID
        leave policy ID
        department ID
        etc.

    The actual resolver configuration is controlled by
    RESOLVER_CONFIG.
    """

    return HealthIdResolver(
        health_client,
        RESOLVER_CONFIG,
    )